### ISSUE TITLE
help

### ISSUE THREAD

**Issue by hu-chia** [Darren-chenchen/IDealist#3]
![image](https://user-images.githubusercontent.com/13718160/56132375-6258fc00-5fbc-11e9-89a7-ab06ba776831.png)

**Comment by Darren-chenchen** [comment]
你的xcode版本是多少

**Comment by hu-chia** [comment]
> 你的xcode版本是多少

最新版的xcode，`Version 10.2 (10E125)`

**Comment by Darren-chenchen** [comment]
已修复  0.0.5
